name = "melonrpc"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# KV namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5e0ccf34ddc24afda02dfa9d7d7b038b"

# Static assets
[site]
bucket = "./public"

# Custom domain (uncomment when ready)
# [env.production]
# routes = [
#   { pattern = "melonrpc.click", custom_domain = true }
# ]
